set_property PACKAGE_PIN H19 [get_ports sysclk_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sysclk_p]
set_property PACKAGE_PIN G18 [get_ports sysclk_n]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sysclk_n]
set_property PACKAGE_PIN AU39 [get_ports gpio_led_7_ls]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_led_7_ls]
set_property PACKAGE_PIN AP42 [get_ports gpio_led_6_ls]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_led_6_ls]
set_property PACKAGE_PIN AP41 [get_ports gpio_led_5_ls]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_led_5_ls]
set_property PACKAGE_PIN AR35 [get_ports gpio_led_4_ls]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_led_4_ls]
set_property PACKAGE_PIN AT37 [get_ports gpio_led_3_ls]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_led_3_ls]
set_property PACKAGE_PIN AR37 [get_ports gpio_led_2_ls]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_led_2_ls]
set_property PACKAGE_PIN AN39 [get_ports gpio_led_1_ls]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_led_1_ls]
set_property PACKAGE_PIN AM39 [get_ports gpio_led_0_ls]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_led_0_ls]
set_property PACKAGE_PIN AY33 [get_ports gpio_dip_sw1]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_dip_sw1]


